from plainsolid import *

# A CM proposal opened for review: the stand-in assembly generated by
# zoo/vendor/gen_node_stub.py, with its hierarchy, names and colours.
meta(kind="assembly", name="node_review", revision="A")

node = import_step("node", "vendor/node_stub.step")
