"""Generate browser edit types from the engine's Pydantic contract.

Run with `uv run python scripts/generate_edit_types.py`; CI uses --check.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from plainsolid.operations import EDIT_ADAPTER

TARGET = Path(__file__).resolve().parents[1] / "web/src/api/operations.ts"


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        import json

        return json.dumps(schema["const"])
    for union in ("anyOf", "oneOf"):
        if union in schema:
            return " | ".join(dict.fromkeys(ts_type(s) for s in schema[union]))
    kind = schema.get("type")
    if kind == "array":
        if "prefixItems" in schema:
            return "[" + ", ".join(ts_type(s) for s in schema["prefixItems"]) + "]"
        return f"Array<{ts_type(schema['items'])}>"
    if kind == "object":
        fields = [
            f"{key}{'' if key in schema.get('required', []) else '?'}: {ts_type(value)}"
            for key, value in schema.get("properties", {}).items()
        ]
        if "additionalProperties" in schema and schema["additionalProperties"] is not False:
            return "{ [key: string]: " + ts_type(schema["additionalProperties"]) + " }"
        return "{ " + "; ".join(fields) + " }"
    primitives = {
        "string": "string",
        "number": "number",
        "integer": "number",
        "boolean": "boolean",
        "null": "null",
    }
    if kind not in primitives:
        raise ValueError(f"unsupported schema in edit contract: {schema}")
    return primitives[kind]


def generated() -> str:
    schema = EDIT_ADAPTER.json_schema()
    definitions = schema.pop("$defs")
    return (
        "// Generated by scripts/generate_edit_types.py. Do not edit by hand.\n"
        + "\n".join(
            f"export type {name} = {ts_type(value)};" for name, value in definitions.items()
        )
        + f"\n\nexport type EditOp = {ts_type(schema)};\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generated()
    if args.check:
        if not TARGET.exists() or TARGET.read_text() != content:
            raise SystemExit(
                "Edit types are stale; run uv run python scripts/generate_edit_types.py"
            )
    else:
        TARGET.write_text(content)
